<?php
include_once("config.php");
if (isset($_GET["all"]))
{
    $SQL = "
    DROP TABLE IF EXISTS `idf`;
    DROP TABLE IF EXISTS `sentence`;
    DROP TABLE IF EXISTS `searchresult`;
    DROP TABLE IF EXISTS `search`;
    DROP TABLE IF EXISTS `WhiteList`;

    CREATE TABLE IF NOT EXISTS `idf` (
    `idfid` int(11) NOT NULL,
    `idfstring` varchar(4) NOT NULL,
    `idfnumber` varchar(50) NOT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ALTER TABLE `idf` ADD PRIMARY KEY (`idfid`);
    ALTER TABLE `idf` MODIFY `idfid` int(11) NOT NULL AUTO_INCREMENT;

    
    CREATE TABLE IF NOT EXISTS `search` (
    `SearchId` int(11) NOT NULL,
    `SearchString` varchar(100) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `search` ADD PRIMARY KEY (`SearchId`);
    ALTER TABLE `search` MODIFY `SearchId` int(11) NOT NULL AUTO_INCREMENT;

    
    CREATE TABLE IF NOT EXISTS `searchresult` (
    `SearchResultId` int(11) NOT NULL,
    `SearchId` int(11) NOT NULL,
    `WhiteListId` int(11) NOT NULL DEFAULT '0',
    `SearchResultRate` double NOT NULL,
    `Link` varchar(1000) NOT NULL,
    `Title` varchar(1000) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `searchresult` ADD PRIMARY KEY (`SearchResultId`);
    ALTER TABLE `searchresult` MODIFY `SearchResultId` int(11) NOT NULL AUTO_INCREMENT;
    ALTER TABLE `searchresult` ADD  CONSTRAINT `SearchId` FOREIGN KEY (`SearchId`) REFERENCES `search`(`SearchId`) ON DELETE CASCADE ON UPDATE RESTRICT;

    
    CREATE TABLE IF NOT EXISTS `sentence` (
    `sentence_id` int(11) NOT NULL,
    `search_result_id` int(11) NOT NULL,
    `sentences` longtext NOT NULL,
    `sentence_grade` double NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `sentence` ADD PRIMARY KEY (`sentence_id`), ADD KEY `search_result_id` (`search_result_id`);
    ALTER TABLE `sentence` MODIFY `sentence_id` int(11) NOT NULL AUTO_INCREMENT;
    ALTER TABLE `sentence` ADD CONSTRAINT `search_result_id` FOREIGN KEY (`search_result_id`) REFERENCES `searchresult` (`SearchResultId`);

    CREATE TABLE IF NOT EXISTS `WhiteList` (
    `WhiteListId` int(10) UNSIGNED NOT NULL,
    `WhiteListName` varchar(50) NOT NULL,
    `WhiteListClass` int(11) NOT NULL,
    `WhiteListLink` varchar(1000) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    INSERT INTO `WhiteList` (`WhiteListId`, `WhiteListName`, `WhiteListClass`, `WhiteListLink`) VALUES
    (0, '其他', 0, 'https://mi2020.tcu.app'),
    (1, '衛生福利部', 1, 'https://www.mohw.gov.tw/'),
    (2, '衛生福利部中央健康保險署', 1, 'https://www.nhi.gov.tw/'),
    (3, '衛生福利部疾病管制署', 1, 'https://www.cdc.gov.tw/'),
    (4, '衛生福利部食品藥物管理署', 1, 'https://www.fda.gov.tw/'),
    (5, '衛生福利部國民健康署', 1, 'https://www.hpa.gov.tw/'),
    (6, '衛生福利部社會及家庭署', 1, 'https://www.sfaa.gov.tw/'),
    (7, '衛生福利部國家中醫藥研究所', 1, 'https://www.nricm.edu.tw/'),
    (8, '國家衛生研究院 (NHRI)', 1, 'https://www.nhri.edu.tw/'),
    (9, '世界衛生組織 (WHO)', 1, 'https://www.who.int/zh'),
    (10, '國防醫學院全球資訊網', 1, 'https://www.ndmctsgh.edu.tw/'),
    (11, '中央研究院', 1, 'https://www.sinica.edu.tw/'),
    (12, '中央研究院細胞與個體生物學研究所', 1, 'http://icob.sinica.edu.tw/'),
    (13, '中央研究院基因體研究中心', 1, 'http://www.genomics.sinica.edu.tw/'),
    (14, '中央研究院生醫轉譯研究中心', 1, 'https://biotrec.sinica.edu.tw/'),
    (15, '怡仁綜合醫院', 2, 'http://www.yeezen.com.tw/'),
    (16, '七賢脊椎外科醫院', 2, 'http://www.spine.com.tw/'),
    (17, '乃榮醫療社團法人乃榮醫院', 2, 'https://www.naijung.com.tw/'),
    (18, '三軍總醫院', 2, 'http://www.tsgh.ndmctsgh.edu.tw/'),
    (19, '三軍總醫院北投分院', 2, 'https://beitou.tsgh.ndmctsgh.edu.tw/'),
    (20, '三軍總醫院松山分院', 2, 'https://songshan.tsgh.ndmctsgh.edu.tw/'),
    (21, '三軍總醫院基隆分院', 2, 'https://keelung.tsgh.ndmctsgh.edu.tw/'),
    (22, '三軍總醫院澎湖分院', 2, 'https://afph.tsgh.ndmctsgh.edu.tw/'),
    (23, '三重中興醫院', 2, 'http://www.cs-hospital.org.tw/'),
    (24, '三重宏仁醫院', 2, 'http://mail.hrh.com.tw/'),
    (25, '三重祐民綜合醫院', 2, 'http://www.symh.com.tw/'),
    (26, '上琳醫院', 2, 'http://www.shanglin.tidi.tw/'),
    (27, '大千綜合醫院', 2, 'http://www.dachien.com.tw/'),
    (28, '大千醫療社團法人南勢醫院', 2, 'http://www.dachien.com.tw/schedule.php?xid=3'),
    (29, '大川醫院', 2, 'http://www.dachuan.com.tw/'),
    (30, '大安醫院', 2, 'http://www.daanhosp.com.tw/web/'),
    (31, '大明醫院', 2, 'http://www.taminga.com.tw/'),
    (32, '大東醫院', 2, 'http://www.da-dong.com.tw/'),
    (33, '大眾醫院', 2, 'http://www.jiahuo.com.tw/'),
    (34, '大順醫院', 2, 'http://www.dashuen.com.tw/'),
    (35, '大園敏盛醫院', 2, 'http://www.e-ms.com.tw/SubWeb/Mb/msd.html'),
    (36, '大新醫院', 2, 'http://www.mashup.com.tw/dasin/'),
    (37, '中山醫學大學附設醫院', 2, 'http://www.csh.org.tw/'),
    (38, '中山醫學大學附設醫院中興分院', 2, 'http://www.csh.org.tw/cs/'),
    (39, '中山醫療社團法人中山醫院', 2, 'http://www.csh.com.tw/'),
    (40, '中心診所醫療財團法人中心綜合醫院', 2, 'https://www.clinic.org.tw/'),
    (41, '中正脊椎骨科醫院', 2, 'http://www.jjoh.org/'),
    (42, '中美醫院', 2, 'https://www.e-zm.com.tw/'),
    (43, '中英醫療社團法人中英醫院', 2, 'http://www.choninn.com.tw/'),
    (44, '中英醫療社團法人板英醫院', 2, 'http://www.panying.com.tw/'),
    (45, '中國醫藥大學北港附設醫院', 2, 'http://www2.bh.cmu.edu.tw/'),
    (46, '中國醫藥大學兒童醫院', 2, 'http://www.cmuch.org.tw/'),
    (47, '中國醫藥大學附設醫院', 2, 'http://www.cmuh.cmu.edu.tw/'),
    (48, '中國醫藥大學附設醫院草屯分院', 2, 'https://www.cmuh.cmu.edu.tw/'),
    (49, '中國醫藥大學新竹附設醫院', 2, 'http://www.cmu-hch.cmu.edu.tw/'),
    (50, '中壢長榮醫院', 2, 'http://www.egh.com.tw/'),
    (51, '尹書田紀念醫院', 2, 'http://www.shutien.org.tw/'),
    (52, '仁安醫院', 2, 'http://www.union.org/'),
    (53, '仁村醫院', 2, 'http://www.jen-chun.com.tw/'),
    (54, '仁和醫院', 2, 'http://www.jhshow.org.tw/'),
    (55, '仁愛醫院', 2, 'http://www.rah.com.tw/'),
    (56, '仁愛醫療社團法人仁愛醫院', 2, 'http://www.tnjenaihos.org.tw/'),
    (57, '仁愛醫療財團法人仁愛醫院', 2, 'http://www.jah.org.tw/'),
    (58, '仁德醫療社團法人陳仁德醫院', 2, 'https://www.jdhc.org.tw/'),
    (59, '元復醫院', 2, 'http://www.youngforehospital.com/'),
    (60, '天主教中華聖母修女會醫療財團法人天主教聖馬爾定醫院', 2, 'http://www.stm.org.tw/'),
    (61, '天主教中華道明修女會醫療財團法人天主教福安醫院', 2, 'http://www.fah.org.tw/'),
    (62, '天主教仁慈醫療財團法人仁慈醫院', 2, 'http://www.mercy.org.tw/'),
    (63, '天主教花蓮教區醫療財團法人台東聖母醫院', 2, 'https://www.st-mary.org.tw/'),
    (64, '天主教若瑟醫療財團法人若瑟醫院', 2, 'http://www.stjoho.org.tw/'),
    (65, '天主教耕莘醫療財團法人耕莘醫院', 2, 'http://eng.cth.org.tw/'),
    (66, '天主教聖功醫療財團法人聖功醫院', 2, 'http://www.joseph.org.tw/'),
    (67, '天主教靈醫會醫療財團法人惠民醫院', 2, 'http://www.penhu.net/9271750/'),
    (68, '天主教靈醫會醫療財團法人羅東聖母醫院', 2, 'http://www.smh.org.tw/'),
    (69, '天成醫療社團法人天晟醫院', 2, 'http://www.tcmg.com.tw/'),
    (70, '文雄醫院', 2, 'http://www.wen-hsiung.com.tw/'),
    (71, '北港仁一醫院', 2, 'http://www.ren-yi.com.tw/'),
    (72, '北新醫療社團法人北新醫院', 2, 'http://peihsin.com.tw/'),
    (73, '台北協和婦女醫院', 2, 'https://www.woman.org.tw/'),
    (74, '台新醫院', 2, 'https://www.ts-h.com.tw/'),
    (75, '台灣基督長老教會馬偕醫療財團法人台東馬偕紀念醫院', 2, 'http://ttw3.mmh.org.tw/'),
    (76, '台灣基督長老教會馬偕醫療財團法人馬偕紀念醫院', 2, 'http://www.mmh.org.tw/'),
    (77, '台灣基督長老教會馬偕醫療財團法人新竹馬偕紀念醫院', 2, 'http://www.hc.mmh.org.tw/'),
    (78, '台灣基督長老教會新樓醫療財團法人台南新樓醫院', 2, 'http://www.sinlau.org.tw/'),
    (79, '右昌聯合醫院', 2, 'http://www.ycuh.com.tw/'),
    (80, '四季台安醫院', 2, 'https://taianhospital.com.tw/'),
    (81, '平和醫療社團法人和平醫院', 2, 'http://www.peacehospital.url.tw/'),
    (82, '平鎮陽明醫院', 2, 'http://www.yangminpj.com.tw/'),
    (83, '弘光科技大學附設老人醫院', 2, 'http://ach.hk.edu.tw/'),
    (84, '本堂澄清醫院', 2, 'http://www.bentang.com.tw/'),
    (85, '民族婦產科家醫科醫院', 2, 'http://mthospital.com.tw/'),
    (86, '民族醫院', 2, 'http://www.mthospital.com.tw/'),
    (87, '永川醫院', 2, 'http://www.ychospital.org/'),
    (88, '永和復康醫院', 2, 'http://www.fuconhosp.com.tw/'),
    (89, '永和醫院', 2, 'http://www.yungho.com.tw/'),
    (90, '永聖醫療社團法人文化醫院', 2, 'http://twhospital.org/'),
    (91, '永達醫療社團法人永達護理之家', 2, 'http://www.2311111.hos.tw/'),
    (92, '生安婦產小兒科醫院', 2, 'http://www.sanhospital.com.tw/'),
    (93, '光田醫療社團法人光田綜合醫院', 2, 'http://www.ktgh.com.tw/'),
    (94, '光雄長安醫院', 2, 'http://www.khca.com.tw/'),
    (95, '全生醫院', 2, 'http://chuansheng.com.tw/'),
    (96, '吉田耳鼻喉科醫院', 2, 'http://go-gen.com/'),
    (97, '吉安醫療社團法人吉安醫院', 2, 'http://www.jianhspt.com.tw/'),
    (98, '同仁院醫療財團法人萬華醫院', 2, 'https://wanhua.rghealth.com.tw/'),
    (99, '同仁醫院', 2, 'http://www.tjh.org.tw/'),
    (100, '安心醫院', 2, 'http://www.tjh.com.tw/'),
    (101, '安生醫院', 2, 'http://www.安生.tw/'),
    (102, '安和醫療社團法人安和醫院', 2, 'http://www.ah-hosp.com.tw/'),
    (103, '安泰醫療社團法人安泰醫院', 2, 'http://www.tsmh.com.tw/'),
    (104, '安泰醫療社團法人潮州安泰醫院', 2, 'http://www.tsmh.org.tw/sites/web_cz/show_web_page.php?edsno=29'),
    (105, '成美醫院', 2, 'http://www.chainmay.com.tw/'),
    (106, '竹山秀傳醫院', 2, 'http://www.csshow.org.tw/'),
    (107, '竹信醫院', 2, 'http://www.chushin.com.tw/'),
    (108, '行天宮醫療志業醫療財團法人恩主公醫院', 2, 'http://www.eck.org.tw/'),
    (109, '西園醫療社團法人西園醫院', 2, 'http://www.westgarden.com.tw/'),
    (110, '伸港忠孝醫院', 2, 'http://ren.smartweb.tw/'),
    (111, '佑民醫療社團法人佑民醫院', 2, 'http://www.yumin.com.tw/'),
    (112, '佑青醫療財團法人佑青醫院', 2, 'http://www.yochin.org.tw/'),
    (113, '佑霖診所(原)佑林醫院', 2, 'https://www.yolinclinic.com.tw/'),
    (114, '佛教慈濟醫療財團法人大林慈濟醫院', 2, 'http://dalin.tzuchi.com.tw/'),
    (115, '佛教慈濟醫療財團法人斗六慈濟醫院', 2, 'https://app.tzuchi.com.tw/tchw/OpdReg/SecList_TL.aspx'),
    (116, '佛教慈濟醫療財團法人台北慈濟醫院', 2, 'http://taipei.tzuchi.com.tw/'),
    (117, '佛教慈濟醫療財團法人玉里慈濟醫院', 2, 'http://yuli.tzuchi.com.tw/'),
    (118, '佛教慈濟醫療財團法人花蓮慈濟醫院', 2, 'http://www.tzuchi.com.tw/'),
    (119, '佛教慈濟醫療財團法人臺中慈濟醫院', 2, 'http://taichung.tzuchi.com.tw/'),
    (120, '佛教慈濟醫療財團法人關山慈濟醫院', 2, 'http://kuanshan.tzuchi.com.tw/'),
    (121, '吳昆哲婦產小兒科醫院', 2, 'https://www.drwuhospital.com.tw/'),
    (122, '宋志懿醫院', 2, 'https://scyhospital.webnode.tw/'),
    (123, '宋俊宏婦幼醫院', 2, 'http://soonghospital.com.tw/'),
    (124, '宏其醫療社團法人宏其婦幼醫院', 2, 'http://www.hungchihospital.org.tw/'),
    (125, '宏恩醫院', 2, 'http://hong-en.com.tw/'),
    (126, '宏恩醫療財團法人宏恩綜合醫院', 2, 'http://www.country.org.tw/'),
    (127, '志誠醫院', 2, 'http://www.c-c-chen.com.tw/'),
    (128, '李綜合醫療社團法人李綜合醫院', 2, 'http://www.leehospital.com.tw/'),
    (129, '杏和醫院', 2, 'http://hhh.smh.org.tw/'),
    (130, '杏豐醫院', 2, 'http://singfong.com/'),
    (131, '沙爾德聖保祿修女會醫療財團法人聖保祿醫院', 2, 'https://www.sph.org.tw/'),
    (132, '秀傳醫療社團法人秀傳紀念醫院', 2, 'https://www.scmh.org.tw/'),
    (133, '秀傳醫療財團法人彰濱秀傳紀念醫院', 2, 'https://www.cbshow.org.tw/'),
    (134, '阮綜合醫療社團法人阮綜合醫院', 2, 'http://www.yuanhosp.com.tw/'),
    (135, '亞東紀念醫院', 2, 'https://www.femh.org.tw/'),
    (136, '亞洲大學附屬醫院', 2, 'https://www.auh.org.tw/'),
    (137, '佳里新生醫院', 2, 'http://www.hosp-shinsen.com.tw/'),
    (138, '佳欣婦幼醫院', 2, 'http://www.cswch.com.tw/'),
    (139, '卓醫院', 2, 'http://www.chohp.com.tw/'),
    (140, '周宗盛醫院', 2, 'http://obsgynchou.com.tw/'),
    (141, '奇美醫療財團法人奇美醫院', 2, 'http://www.chimei.org.tw/'),
    (142, '宜蘭仁愛醫療財團法人宜蘭仁愛醫院', 2, 'http://www.jen-ai.org.tw/'),
    (143, '宜蘭員山醫療財團法人宜蘭員山醫院', 2, 'http://www.pumen.org.tw/'),
    (144, '居善醫院', 2, 'http://www.jushan.com.tw/'),
    (145, '怡和醫院', 2, 'http://www.yiher.com.tw/'),
    (146, '怡濟慈園醫療社團法人宏濟神經精神科醫院', 2, 'https://newhongchi.com/'),
    (147, '承安醫院', 2, 'http://www.camis.com.tw/'),
    (148, '明德醫院', 2, 'http://www.minder.url.tw/'),
    (149, '東元醫療社團法人東元綜合醫院', 2, 'https://w3.tyh.com.tw/'),
    (150, '東基醫療財團法人台東基督教醫院', 2, 'https://www.tch.org.tw/'),
    (151, '東華醫院', 2, 'http://www.dong.org.tw/'),
    (152, '東勢區農會附設農民醫院', 2, 'http://www.fh.org.tw/'),
    (153, '板新醫院', 2, 'http://www.panshin.com.tw/'),
    (154, '板橋中興醫院', 2, 'http://www.pcchh.com.tw/'),
    (155, '板橋國泰醫院', 2, 'http://pcch.com.tw/'),
    (156, '林森醫院', 2, 'http://www.lshp.com.tw/'),
    (157, '林新醫療社團法人林新醫院', 2, 'http://www.lshosp.com.tw/'),
    (158, '林新醫療社團法人烏日林新醫院', 2, 'http://www.wlshosp.org.tw/'),
    (159, '林醫院', 2, 'https://dialysislin.com/'),
    (160, '秉坤婦幼醫院', 2, 'http://www.binkun.com.tw/'),
    (161, '育仁醫院', 2, 'https://yuzenhospital.wixsite.com/yuzenhospital'),
    (162, '邱外科醫院', 2, 'http://www.chiuhospital.com.tw/'),
    (163, '金安心醫院', 2, 'http://www.artemishosp.com/'),
    (164, '長庚醫療財團法人長庚紀念醫院', 2, 'https://www.cgmh.org.tw/'),
    (165, '長庚醫療財團法人桃園長庚紀念醫院', 2, 'https://www.cgmh.org.tw/tw/Systems/AreaInfo/6'),
    (166, '長春醫院', 2, 'http://www.everlife.com.tw/'),
    (167, '長慎醫院', 2, 'http://www.chansn.com.tw/'),
    (168, '信一骨科醫院', 2, 'https://www.onetrust.com.tw/'),
    (169, '信生醫院', 2, 'http://www.hsh119.hos.tw/'),
    (170, '信安醫療社團法人信安醫院', 2, 'http://www.hsinan.com.tw/'),
    (171, '信義醫療財團法人高雄基督教醫院', 2, 'http://www.kch.org.tw/'),
    (172, '冠華醫院', 2, 'http://khh.tnn.tw/'),
    (173, '南光神經精神科醫院', 2, 'http://www.nk-ph.com/'),
    (174, '南門綜合醫院', 2, 'http://www.nanmen.com.tw/'),
    (175, '南門醫療社團法人南門醫院', 2, 'http://www.nanmen.org.tw/'),
    (176, '南星醫院', 2, 'http://www.southstarhospital.com/'),
    (177, '屏安醫療社團法人屏安醫院', 2, 'http://www.pingan.url.tw/sean/modules/tinyd0/'),
    (178, '屏東民眾醫院', 2, 'http://www.hospital-ez.com.tw/'),
    (179, '屏基醫療財團法人屏東基督教醫院', 2, 'http://www.ptch.org.tw/'),
    (180, '建生診所', 2, 'http://www.cv5555366.com.tw/'),
    (181, '建佑醫院', 2, 'http://www.chien-yu.com.tw/'),
    (182, '恆基醫療財團法人恆春基督教醫院', 2, 'http://www.hcch.org.tw/'),
    (183, '柏仁醫院', 2, 'http://www.pojen.com.tw/'),
    (184, '洪外科醫院', 2, 'http://www.hsh.tw/'),
    (185, '洪宗鄰醫療社團法人洪宗鄰醫院', 2, 'http://www.htlh.com.tw/'),
    (186, '洪揚醫院', 2, 'http://www.hygh.com.tw/'),
    (187, '活力得中山脊椎外科醫院', 2, 'http://www.lohas-spine.com/'),
    (188, '為恭醫療財團法人為恭紀念醫院(崇仁醫院)', 2, 'http://www.weigong.org.tw/'),
    (189, '美德醫院', 2, 'http://www.leehospital.com.tw/meide/'),
    (190, '茂盛醫院', 2, 'https://www.ivftaiwan.tw/'),
    (191, '茂隆骨科醫院', 2, 'http://www.mlbone.com.tw/'),
    (192, '迦樂醫療財團法人迦樂醫院', 2, 'https://caloh.org.tw/'),
    (193, '重仁骨科醫院', 2, 'http://www.chung-jen.com.tw/'),
    (194, '重光醫院', 2, 'http://www.chorng-guang.url.tw/'),
    (195, '員生醫院', 2, 'http://www.ysh.org.tw/'),
    (196, '員林何醫院', 2, 'http://www.ho-lin.com.tw/'),
    (197, '員林郭醫院大村分院', 2, 'http://www.kuohospital.com.tw/'),
    (198, '員郭醫院', 2, 'http://www.yuankuo.com.tw/'),
    (199, '員榮醫療社團法人員榮醫院', 2, 'http://www.yuanrung.com.tw/'),
    (200, '埔基醫療財團法人埔里基督教醫院', 2, 'https://www.pch.org.tw/'),
    (201, '恩樺醫院', 2, 'https://enhua.com.tw/'),
    (202, '振興醫療財團法人振興醫院', 2, 'https://www.chgh.org.tw/'),
    (203, '晉生醫療社團法人晉生慢性醫院', 2, 'http://www.jshospital.com.tw/'),
    (204, '泰安醫院', 2, 'https://taian.rghealth.com.tw/'),
    (205, '泰和醫院', 2, 'http://taihohosp.com.tw/'),
    (206, '海天醫療社團法人海天醫院', 2, 'https://hiten.pixnet.net/blog'),
    (207, '烏日澄清醫院', 2, 'http://www.wjcch.com.tw/'),
    (208, '益民醫院', 2, 'http://www.yim.org.tw/'),
    (209, '祐民醫院', 2, 'http://www.yowmin.com.tw/'),
    (210, '祐生醫院', 2, 'http://www.yuoshen.com.tw/'),
    (211, '財團法人台灣省私立台中仁愛之家附設靜和醫院	', 2, 'http://www.cott.org.tw/'),
    (212, '財團法人台灣省私立台北仁濟院附設仁濟醫院', 2, 'http://www.tjci-sj.org.tw/'),
    (213, '財團法人台灣省私立台南仁愛之家', 2, 'http://www.thop.org.tw/'),
    (214, '財團法人台灣省私立桃園仁愛之家附設新竹新生醫院', 2, 'http://www.hcnb.com.tw/'),
    (215, '財團法人台灣省私立高雄仁愛之家附設慈惠醫院', 2, 'http://thmh.khja.org.tw/'),
    (216, '財團法人私立高雄醫學大學附設中和紀念醫院', 2, 'http://www.kmuh.org.tw/'),
    (217, '財團法人臺灣省私立桃園仁愛之家附設苗栗新生醫院', 2, 'http://www.sinsheng.com.tw/'),
    (218, '馬偕兒童醫院', 2, 'https://www2.mmh.org.tw/childrens/'),
    (219, '馬偕紀念醫院淡水院區', 2, 'https://tsreg.mmh.org.tw/'),
    (220, '高雄市立大同醫院', 2, 'http://www.kmtth.org.tw/'),
    (221, '高雄市立小港醫院', 2, 'http://www.kmhk.org.tw/'),
    (222, '高雄市立民生醫院', 2, 'https://kmsh.kcg.gov.tw/'),
    (223, '高雄市立岡山醫院（秀傳醫療社團法人）', 2, 'https://www.ks.org.tw/'),
    (224, '高雄市立凱旋醫院', 2, 'https://ksph.kcg.gov.tw/'),
    (225, '高雄市立旗津醫院(財團法人私立高雄醫學大學)	', 2, 'http://www.kmch.org.tw/'),
    (226, '高雄市立鳳山醫院（長庚醫療財團法人）', 2, 'https://www.cgmh.org.tw/tw/Systems/AreaInfo/11'),
    (227, '高雄市立聯合醫院', 2, 'http://www.kmuh.gov.tw/'),
    (228, '高雄榮民總醫院', 2, 'https://www.vghks.gov.tw/'),
    (229, '高雄榮民總醫院屏東分院', 2, 'http://www.vhlc.gov.tw/'),
    (230, '高雄榮民總醫院臺南分院', 2, 'https://www.vhyk.gov.tw/'),
    (231, '高新醫院', 2, 'https://www.ksh.url.tw/'),
    (232, '健仁醫院', 2, 'http://www.jiannren.org.tw/'),
    (233, '健新醫院', 2, 'http://www.cshospital.com.tw/'),
    (234, '國仁醫院', 2, 'http://www.golden-hospital.com.tw/'),
    (235, '國立成功大學醫學院附設醫院', 2, 'http://www.hosp.ncku.edu.tw/'),
    (236, '國立成功大學醫學院附設醫院斗六分院', 2, 'http://d6www.hosp.ncku.edu.tw/'),
    (237, '國立陽明大學附設醫院', 2, 'https://www.ymuh.ym.edu.tw/'),
    (238, '國立臺灣大學醫學院附設癌醫中心醫院', 2, 'http://www.ntucc.gov.tw/'),
    (239, '國立臺灣大學醫學院附設醫院', 2, 'http://www.ntuh.gov.tw/'),
    (240, '國立臺灣大學醫學院附設醫院北護分院', 2, 'https://www.bh.ntuh.gov.tw/'),
    (241, '國立臺灣大學醫學院附設醫院竹東分院', 2, 'http://www.chut.ntuh.gov.tw/'),
    (242, '國立臺灣大學醫學院附設醫院兒童醫院', 2, 'https://www.ntuh.gov.tw/ntuch'),
    (243, '國立臺灣大學醫學院附設醫院金山分院', 2, 'https://www.js.ntuh.gov.tw/'),
    (244, '國立臺灣大學醫學院附設醫院雲林分院', 2, 'https://www.ylh.gov.tw/'),
    (245, '國立臺灣大學醫學院附設醫院新竹分院', 2, 'https://www.hch.gov.tw/'),
    (246, '國立臺灣大學醫學院附設醫院新竹生醫園區分院', 2, 'https://bih.hch.gov.tw/'),
    (247, '國軍台中總醫院', 2, 'https://803.mnd.gov.tw/'),
    (248, '國軍花蓮總醫院', 2, 'https://805.mnd.gov.tw/'),
    (249, '國軍桃園總醫院', 2, 'https://www.aftygh.gov.tw/'),
    (250, '國軍高雄總醫院', 2, 'https://802.mnd.gov.tw/'),
    (251, '國軍高雄總醫院岡山分院', 2, 'http://reg.814.mnd.gov.tw/'),
    (252, '國軍新竹地區醫院', 2, 'https://813.mnd.gov.tw/'),
    (253, '國泰醫療財團法人汐止國泰', 2, 'http://sijhih.cgh.org.tw/'),
    (254, '國泰醫療財團法人國泰綜合醫院', 2, 'https://www.cgh.org.tw/'),
    (255, '國泰醫療財團法人新竹國泰綜合醫院', 2, 'http://hsinchu.cgh.org.tw/'),
    (256, '培靈醫院', 2, 'http://www.peiling.tw/'),
    (257, '培靈醫療社團法人關西醫院', 2, 'https://peiling.azurewebsites.net/'),
    (258, '基隆市立醫院', 2, 'http://www.kmh.gov.tw/'),
    (259, '基督復臨安息日會醫療財團法人臺安醫院', 2, 'http://www.tahsda.org.tw/'),
    (260, '康寧醫療財團法人康寧醫院', 2, 'http://www.knh.org.tw/'),
    (261, '敏盛綜合醫院', 2, 'http://www.e-ms.com.tw/'),
    (262, '梓榮醫療社團法人弘大醫院', 2, 'http://www.hopedoctors.com.tw/'),
    (263, '清泉醫院', 2, 'http://www.ching-chyuan.com.tw/'),
    (264, '清海醫院', 2, 'https://www.chinghaih.com/'),
    (265, '清濱醫院', 2, 'http://www.chibibing.url.tw/'),
    (266, '祥恩醫院', 2, 'http://www.xiang-en.com.tw/'),
    (267, '祥顥醫院', 2, 'https://www.hhhosp.com.tw/'),
    (268, '第一醫院', 2, 'http://www.di-yi.com.tw/'),
    (269, '通霄光田醫院', 2, 'http://www.ts.ktgh.com.tw/'),
    (270, '連江縣立醫院', 2, 'https://www.matsuh.gov.tw/'),
    (271, '郭綜合醫院', 2, 'http://www.kgh.com.tw/'),
    (272, '陳澤彥婦產科醫院', 2, 'https://www.cty-obs.com.tw/'),
    (273, '勝美醫院', 2, 'http://www.sheng-mei.com.tw/'),
    (274, '博仁綜合醫院', 2, 'http://www.pojengh.com.tw/'),
    (275, '博愛疝氣專科醫院', 2, 'https://www.hernia.com.tw/'),
    (276, '博愛蕙馨醫院', 2, 'https://www.boaihs.com.tw/'),
    (277, '復興醫療社團法人復興醫院', 2, 'http://www.fusing.org.tw/'),
    (278, '惠川醫院', 2, 'http://www.hui-healthy.com.tw/'),
    (279, '惠仁醫院', 2, 'http://www.hui-healthy.com.tw/'),
    (280, '惠來醫療社團法人宏仁醫院', 2, 'http://www.hongren.com.tw/'),
    (281, '惠德醫院', 2, 'http://www.hui-healthy.com.tw/'),
    (282, '敦仁醫院', 2, 'http://www.dunren.com.tw/'),
    (283, '景美醫院', 2, 'http://www.jmh.com.tw/'),
    (284, '曾漢棋綜合醫院', 2, 'http://www.thc-hospital.com.tw/'),
    (285, '皓生醫院', 2, 'http://www.how-baby.com.tw/'),
    (286, '童綜合醫療社團法人童綜合醫院', 2, 'http://www.sltung.com.tw/'),
    (287, '華揚醫院', 2, 'http://www.tyhs.com.tw/'),
    (288, '郵政醫院（中英醫療社團法人）', 2, 'http://www.postal.com.tw/'),
    (289, '鈞安婦幼聯合醫院', 2, 'http://jun-an-hospital.com.tw/'),
    (290, '開元寺慈愛醫院', 2, 'https://2088818.com/'),
    (291, '順安醫院', 2, 'http://www.sanannh.com.tw/'),
    (292, '愛仁醫療社團法人愛仁醫院', 2, 'http://www.airen.com.tw/'),
    (293, '新中興醫院', 2, 'http://www.hcsh.com.tw/'),
    (294, '新仁醫療社團法人新仁醫院', 2, 'http://www.srh.com.tw/'),
    (295, '新太平澄清醫院', 2, 'http://www.ntpcch.com.tw/'),
    (296, '新北仁康醫院', 2, 'http://www.njkh.com.tw/'),
    (297, '新北市立聯合醫院', 2, 'https://www.ntch.ntpc.gov.tw/'),
    (298, '新正薪醫院', 2, 'http://www.health24.com.tw/'),
    (299, '新永和醫院', 2, 'http://www.hsinyungho.com.tw/'),
    (300, '新光吳火獅紀念醫院', 2, 'http://www.skh.org.tw/'),
    (301, '新亞東婦產科醫院', 2, 'https://thcloudsrv.these.com.tw:2096/OpdRegWeb_SYD/'),
    (302, '新昆明醫院', 2, 'http://skmhosp.webnode.tw/'),
    (303, '新泰綜合醫院', 2, 'http://www.sthosp.com.tw/'),
    (304, '新高鳳醫院', 2, 'http://www.keye.com.tw/'),
    (305, '新高醫院', 2, 'http://www.shinkaohosp.com.tw/'),
    (306, '新國民醫療社團法人新國民醫院', 2, 'http://www.skmh.com.tw/'),
    (307, '新菩提醫院', 2, 'http://www.bodhi.com.tw/'),
    (308, '新華醫院', 2, 'http://www.shinhua.tidi.tw/'),
    (309, '新興醫療社團法人新興醫院', 2, 'http://www.syssh.org.tw/'),
    (310, '暘基醫院', 2, 'http://www.yj-phkl.com/'),
    (311, '溫賀睿和醫院', 2, 'http://www.wen-hp.com/'),
    (312, '瑞生醫院', 2, 'http://www.rexsun.idv.tw/'),
    (313, '瑞芳礦工醫院', 2, 'http://www.xn--est231c6ldo0lrzs6og.tw/'),
    (314, '瑞祥醫院', 2, 'http://www.reshhospital.com.tw/'),
    (315, '義大醫療財團法人義大大昌醫院', 2, 'https://edd.edah.org.tw/'),
    (316, '義大醫療財團法人義大癌治療醫院', 2, 'https://edc.edah.org.tw/'),
    (317, '義大醫療財團法人義大醫院', 2, 'https://www.edah.org.tw/'),
    (318, '道安醫院', 2, 'https://www.xn--49s714js3a73j.tw/'),
    (319, '道周醫療社團法人道周醫院', 2, 'http://www.farlinhospital.com/'),
    (320, '達明眼科醫院', 2, 'http://www.derminghosp.com.tw/'),
    (321, '嘉義陽明醫院', 2, 'http://www.ymhospital.com.tw/'),
    (322, '彰化基督教兒童醫院', 2, 'http://www2.cch.org.tw/cmh/'),
    (323, '彰化基督教醫院', 2, 'https://www.cch.org.tw/'),
    (324, '彰化基督教醫療財團法人二林基督教醫院', 2, 'http://www.erhlin.cch.org.tw/'),
    (325, '彰化基督教醫療財團法人南投基督教醫院', 2, 'http://ny.cch.org.tw/'),
    (326, '彰化基督教醫療財團法人員林基督教醫院', 2, 'http://www.bc.cch.org.tw/'),
    (327, '彰化基督教醫療財團法人鹿港基督教醫院', 2, 'http://www.rc.cch.org.tw/'),
    (328, '彰化基督教醫療財團法人雲林基督教醫院', 2, 'http://www.yl.cch.org.tw/'),
    (329, '彰化基督教醫療財團法人彰化基督教醫院', 2, 'http://www.cch.org.tw/'),
    (330, '彰化基督教醫療財團法人漢銘基督教醫院', 2, 'http://www.hm.cch.org.tw/'),
    (331, '慈祐醫院', 2, 'http://www.tyh.org.tw/'),
    (332, '漢銘醫院', 2, 'http://www.hanming.com.tw/'),
    (333, '維新醫療社團法人台中維新醫院', 2, 'http://www.wizcare.com.tw/'),
    (334, '維德醫療社團法人基隆維德醫院', 2, 'http://www.vitahosp.com.tw/'),
    (335, '維馨乳房外科醫院', 2, 'http://www.wsbreast.com/'),
    (336, '臺中榮民總醫院', 2, 'http://www.vghtc.gov.tw/'),
    (337, '臺中榮民總醫院埔里分院', 2, 'http://www.pulivh.gov.tw/'),
    (338, '臺中榮民總醫院嘉義分院', 2, 'https://www.vhcy.gov.tw/'),
    (339, '臺中榮民總醫院灣橋分院', 2, 'https://www.vhwc.gov.tw/'),
    (340, '臺北市立萬芳醫院', 2, 'https://www.wanfang.gov.tw/'),
    (341, '臺北市立聯合醫院', 2, 'https://tpech.gov.taipei/'),
    (342, '臺北市立關渡醫院	', 2, 'http://www.gandau.gov.tw/'),
    (343, '臺北榮民總醫院', 2, 'https://www.vghtpe.gov.tw/'),
    (344, '臺北榮民總醫院玉里分院', 2, 'http://www.vhyl.gov.tw/index.php'),
    (345, '臺北榮民總醫院花東分院', 2, 'http://www.vhtt.gov.tw/'),
    (346, '臺北榮民總醫院員山分院', 2, 'https://www.ysvh.gov.tw/'),
    (347, '臺北榮民總醫院桃園分院', 2, 'http://www.tyvh.gov.tw/'),
    (348, '臺北榮民總醫院新竹分院', 2, 'http://www.vhct.gov.tw/'),
    (349, '臺北榮民總醫院臺東分院', 2, 'http://www.vhtt.gov.tw/'),
    (350, '臺北榮民總醫院鳳林分院', 2, 'http://www.flvh.gov.tw/index.php'),
    (351, '臺北榮民總醫院蘇澳分院', 2, 'https://www.savh.gov.tw/'),
    (352, '臺北醫學大學附設醫院', 2, 'https://www.tmuh.org.tw/'),
    (353, '臺安醫院', 2, 'http://www.tai-an.com.tw/'),
    (354, '臺安醫院雙十分院', 2, 'http://www.tassh.com.tw/'),
    (355, '臺南市立安南醫院', 2, 'http://www.tmanh.org.tw/'),
    (356, '臺南市立醫院', 2, 'https://www.tmh.org.tw/'),
    (357, '臺灣基督教門諾會醫療財團法人門諾醫院', 2, 'https://www.mch.org.tw/'),
    (358, '臺灣基督教門諾會醫療財團法人門諾醫院壽豐分院', 2, 'https://www.mch.org.tw/Docs/618/Default.aspx'),
    (359, '輔仁大學學校財團法人輔仁大學附設醫院', 2, 'https://www.hospital.fju.edu.tw/'),
    (360, '輔英科技大學附設醫院', 2, 'http://www.fy.org.tw/'),
    (361, '劉嘉修醫院', 2, 'https://www.joysure.com.tw/'),
    (362, '廣川醫院', 2, 'http://www.broadriverhospital.com/'),
    (363, '廣聖醫療社團法人廣聖醫院', 2, 'http://www.cs-gsh.com.tw/'),
    (364, '德仁醫院', 2, 'http://www.dazan.tw/'),
    (365, '德謙婦幼醫院', 2, 'http://derchen.so-buy.com/'),
    (366, '慶昇醫療社團法人慶昇醫院', 2, 'http://www.cycsh.org.tw/'),
    (367, '樂生婦幼醫院', 2, 'http://www.happybirth.com.tw/'),
    (368, '澄清復健醫院', 2, 'https://www.ccrh.com.tw/'),
    (369, '澄清綜合醫院', 2, 'http://www.ccgh.com.tw/'),
    (370, '衛生福利部八里療養院', 2, 'https://www.bali.mohw.gov.tw/'),
    (371, '衛生福利部玉里醫院', 2, 'https://www.ttyl.mohw.gov.tw/'),
    (372, '衛生福利部朴子醫院', 2, 'https://www.puzih.mohw.gov.tw/'),
    (373, '衛生福利部花蓮醫院', 2, 'https://www.hwln.mohw.gov.tw/'),
    (374, '衛生福利部花蓮醫院豐濱原住民分院', 2, 'https://www.hwln.mohw.gov.tw/?aid=52&pid=91'),
    (375, '衛生福利部金門醫院', 2, 'https://www.kmhp.mohw.gov.tw/'),
    (376, '衛生福利部南投醫院', 2, 'https://www.nant.mohw.gov.tw/'),
    (377, '衛生福利部屏東醫院', 2, 'https://www.pntn.mohw.gov.tw/'),
    (378, '衛生福利部恆春旅遊醫院', 2, 'https://www.pnhb.mohw.gov.tw/'),
    (379, '衛生福利部苗栗醫院', 2, 'https://www.mil.mohw.gov.tw/'),
    (380, '衛生福利部桃園療養院', 2, 'https://www.typc.mohw.gov.tw/'),
    (381, '衛生福利部桃園醫院', 2, 'https://sw.tygh.mohw.gov.tw/'),
    (382, '衛生福利部桃園醫院新屋分院', 2, 'https://swnetreg.tygh.mohw.gov.tw/'),
    (383, '衛生福利部胸腔病院', 2, 'https://www.ccd.mohw.gov.tw/'),
    (384, '衛生福利部草屯療養院', 2, 'https://www.ttpc.mohw.gov.tw/'),
    (385, '衛生福利部基隆醫院', 2, 'https://www.kln.mohw.gov.tw/'),
    (386, '衛生福利部新營醫院', 2, 'https://www.syh.mohw.gov.tw/'),
    (387, '衛生福利部嘉南療養院', 2, 'https://www.cnpc.mohw.gov.tw/'),
    (388, '衛生福利部嘉義醫院', 2, 'https://www.chyi.mohw.gov.tw/'),
    (389, '衛生福利部彰化醫院', 2, 'https://www.chhw.mohw.gov.tw/'),
    (390, '衛生福利部旗山醫院', 2, 'https://www.chis.mohw.gov.tw/'),
    (391, '衛生福利部臺中醫院', 2, 'https://www.taic.mohw.gov.tw/'),
    (392, '衛生福利部臺北醫院', 2, 'https://www.tph.mohw.gov.tw/'),
    (393, '衛生福利部臺東醫院', 2, 'https://www.tait.mohw.gov.tw/'),
    (394, '衛生福利部臺南醫院', 2, 'https://www.tnhosp.mohw.gov.tw/'),
    (395, '衛生福利部樂生療養院', 2, 'https://www.lslp.mohw.gov.tw/'),
    (396, '衛生福利部澎湖醫院', 2, 'https://www.pngh.mohw.gov.tw/'),
    (397, '衛生福利部豐原醫院', 2, 'https://www.fyh.mohw.gov.tw/'),
    (398, '衛生福利部雙和醫院', 2, 'https://shh.tmu.edu.tw/'),
    (399, '賢德醫院', 2, 'http://www.cender.url.tw/'),
    (400, '鄭婦產科診所', 2, 'http://www.chjspl.com.tw/'),
    (401, '燕巢靜和醫療社團法人燕巢靜和醫院', 2, 'http://www.jing-ho.com.tw/'),
    (402, '璟馨婦幼醫院', 2, 'http://www.lcy-family.com.tw/'),
    (403, '盧亞人醫院', 2, 'http://www.yaren.com.tw/'),
    (404, '蕙生婦幼醫院', 2, 'http://www.fsobs.com.tw/'),
    (405, '蕭中正醫院（清福醫院）', 2, 'http://www.hsiaohospital.org/'),
    (406, '蕭志文醫院', 2, 'http://czwhp.com/'),
    (407, '霖園醫院', 2, 'http://www.linyuan-hosp.com.tw/'),
    (408, '龍潭敏盛醫院', 2, 'http://www.e-ms.com.tw/SubWeb/Mb/msl.html'),
    (409, '優生婦產科醫院', 2, 'http://yusheng-hospital.com.tw/'),
    (410, '優生醫療社團法人優生醫院', 2, 'http://www.yusheng-hospital.com.tw/'),
    (411, '戴銘浚婦兒醫院', 2, 'http://www.dvdh.com.tw/'),
    (412, '戴德森醫療財團法人嘉義基督教醫院', 2, 'http://www.cych.org.tw/'),
    (413, '營新醫院', 2, 'http://www.evernew-hospital.com.tw/'),
    (414, '聯安醫院', 2, 'http://www.anhsp.com.tw/'),
    (415, '聯新國際醫院', 2, 'http://www.landseedhospital.com.tw/lishin/'),
    (416, '聯新國際醫院桃新分院', 2, 'http://www.taoshin.com.tw/'),
    (417, '謝外科醫院', 2, 'http://www.thyroid.com.tw/'),
    (418, '豐榮醫院', 2, 'https://frhosp.rghealth.com.tw/'),
    (419, '醫療財團法人正德癌症醫療基金會佛教正德醫院', 2, 'https://www.bch.org.tw/'),
    (420, '醫療財團法人辜公亮基金會和信治癌中心醫院', 2, 'https://www.kfsyscc.org/m/'),
    (421, '醫療財團法人臺灣區煤礦業基金會臺灣礦工醫院', 2, 'http://twmgh.com/'),
    (422, '醫療財團法人羅許基金會羅東博愛醫院', 2, 'http://www.pohai.org.tw/'),
    (423, '懷寧醫院', 2, 'https://www.armfulcare.com.tw/'),
    (424, '霧峰澄清醫院', 2, 'http://www.wfcc.com.tw/'),
    (425, '寶建醫療社團法人寶建醫院', 2, 'http://www.paochien.com.tw/'),
    (426, '馨蕙馨醫院', 2, 'https://www.shs-h.com.tw/'),
    (427, '中華牙醫學會', 3, 'https://www.ads.org.tw/'),
    (428, '中華民國小兒骨科醫學會', 3, 'http://www.tpos.org.tw/'),
    (429, '中華民國心臟學會', 3, 'http://www.tsoc.org.tw/'),
    (430, '中華民國耳鼻喉科醫學會', 3, 'http://www.tos.org.tw/'),
    (431, '中華民國血液病學會', 3, 'http://www.hematology.org.tw/'),
    (432, '中華民國免疫學會', 3, 'http://www.immunology.org.tw/'),
    (433, '中華民國周產期醫學會', 3, 'https://www.tsop.org.tw/'),
    (434, '中華民國急救加護醫學會', 3, 'https://www.seccm.org.tw/'),
    (435, '中華民國重症醫學會', 3, 'http://www.tsccm.org.tw/'),
    (436, '社團法人中華民國風溼病醫學會', 3, 'http://www.rheumatology.org.tw/'),
    (437, '中華民國核醫醫學會', 3, 'http://www.snm.org.tw/'),
    (438, '社團法人台灣神經外科醫學會', 3, 'https://www.neurosurgery.org.tw/'),
    (439, '中華民國骨科醫學會', 3, 'http://bone.org.tw/'),
    (440, '中華民國眼科醫學會', 3, 'http://www.oph.org.tw/'),
    (441, '中華民國醫師公會全國聯合會', 3, 'https://www.tma.tw/'),
    (442, '中華醫學會', 3, 'http://www.taipei-cma.org/'),
    (443, '台灣小兒外科醫學會', 3, 'https://www.taps.expert/'),
    (444, '台灣小兒神經醫學會', 3, 'http://www.tcns.org.tw/'),
    (445, '台灣內科醫學會', 3, 'http://www.tsim.org.tw/'),
    (446, '台灣外科醫學會', 3, 'http://www.surgery.org.tw/'),
    (447, '台灣生殖醫學會', 3, 'http://www.tsrm.org.tw/htm/'),
    (448, '台灣皮膚科醫學會', 3, 'http://www.derma.org.tw/'),
    (449, '台灣兒科醫學會', 3, 'https://www.pediatr.org.tw/'),
    (450, '台灣泌尿科醫學會', 3, 'http://www.tua.org.tw/'),
    (451, '台灣急診醫學會', 3, 'https://www.sem.org.tw/'),
    (452, '台灣家庭醫學醫學會', 3, 'https://www.tafm.org.tw/'),
    (453, '台灣消化系內視鏡醫學會', 3, 'https://www.dest.org.tw/'),
    (454, '台灣消化系外科醫學會', 3, 'http://www.gis.org.tw/'),
    (455, '台灣胸腔暨重症加護醫學會', 3, 'https://www.tspccm.org.tw/'),
    (456, '台灣婦產科醫學會', 3, 'https://www.taog.org.tw/'),
    (457, '台灣婦癌醫學會', 3, 'http://www.tago.org.tw/'),
    (458, '台灣麻醉醫學會', 3, 'https://www.anesth.org.tw/'),
    (459, '台灣復健醫學會', 3, 'https://www.pmr.org.tw/'),
    (460, '台灣腎臟醫學會', 3, 'https://www.tsn.org.tw/'),
    (461, '台灣感染症醫學會', 3, 'http://www.idsroc.org.tw/'),
    (462, '中華民國環境職業醫學會', 3, 'http://www.eoma.org.tw/'),
    (463, '台灣腦中風學會', 3, 'https://www.stroke.org.tw/'),
    (464, '台灣精神醫學會', 3, 'http://www.sop.org.tw/'),
    (465, '社團法人臺中市醫師公會', 3, 'http://www.tcmed.org.tw/'),
    (466, '財團法人癌症希望基金會', 3, 'https://www.ecancer.org.tw/'),
    (467, '社團法人國家生技醫療產業策進會', 3, 'https://ibmi.taiwan-healthcare.org/'),
    (468, '台北捐血中心', 3, 'http://www.tp.blood.org.tw/'),
    (469, '財團法人中華民國腎臟基金會', 3, 'http://www.kidney.org.tw/'),
    (470, '財團法人肝病防治學術基金會', 3, 'https://www.liver.org.tw/'),
    (471, '醫療財團法人台灣血液基金會', 3, 'http://www.blood.org.tw/'),
    (472, '中華民國心臟病兒童基金會', 3, 'http://www.ccft.org.tw/'),
    (473, '財團法人中華民國兒童燙傷基金會', 3, 'http://www.cbf.org.tw/'),
    (474, '財團法人台灣早產兒基金會', 3, 'https://www.pbf.org.tw/'),
    (475, '社團法人台灣海洋性貧血協會', 3, 'http://www.thala.artcom.tw/'),
    (476, '社團法人中華民國台灣黏多醣症協會', 3, 'http://www.mpssociety.org.tw/'),
    (477, '財團法人中華民國自閉症基金會', 3, 'https://www.fact.org.tw/'),
    (478, '財團法人台灣癌症臨床研究發展基金會', 3, 'http://www.tccf.org.tw/'),
    (479, '財團法人天主教康泰醫療教育基金會', 3, 'http://www.kungtai.org.tw/'),
    (480, '兒童心臟基金會', 3, 'http://www.childheart.org.hk/'),
    (481, '財團法人中華民國婦癌基金會', 3, 'https://www.femalecancer.org.tw/'),
    (482, '中華民國兒童癌症基金會', 3, 'http://www.ccfroc.org.tw/'),
    (483, '財團法人護理人員愛滋病防治基金會', 3, 'http://www.napf.org.tw/'),
    (484, '財團法人台灣醫界聯盟基金會', 3, 'http://www.mpat.org.tw/'),
    (485, '國立清華大學', 4, 'http://www.nthu.edu.tw/'),
    (486, '國立臺灣大學', 4, 'https://www.ntu.edu.tw/'),
    (487, '國立成功大學', 4, 'https://web.ncku.edu.tw/'),
    (488, '國立中興大學', 4, 'https://www.nchu.edu.tw/'),
    (489, '國立陽明大學', 4, 'https://web.ym.edu.tw/'),
    (490, '國立臺東大學', 4, 'https://www.nttu.edu.tw/'),
    (491, '國立金門大學', 4, 'https://www.nqu.edu.tw/'),
    (492, '臺北市立大學', 4, 'https://www.utaipei.edu.tw/'),
    (493, '國立臺灣科技大學', 4, 'https://www.ntust.edu.tw/'),
    (494, '國立臺北護理健康大學', 4, 'https://www.ntunhs.edu.tw/'),
    (495, '國立臺中科技大學', 4, 'https://www.nutc.edu.tw/'),
    (496, '國立臺南護理專科學校', 4, 'https://www.ntin.edu.tw/'),
    (497, '輔仁大學', 4, 'http://www.fju.edu.tw/'),
    (498, '靜宜大學', 4, 'https://www.pu.edu.tw/'),
    (499, '長庚大學', 4, 'https://www.cgu.edu.tw/'),
    (500, '大葉大學', 4, 'https://www.dyu.edu.tw/'),
    (501, '義守大學', 4, 'http://www.isu.edu.tw/'),
    (502, '高雄醫學大學', 4, 'https://www.kmu.edu.tw/'),
    (503, '慈濟學校財團法人慈濟大學', 4, 'https://www.tcu.edu.tw/'),
    (504, '臺北醫學大學', 4, 'http://www.tmu.edu.tw/'),
    (505, '中山醫學大學', 4, 'http://www.csmu.edu.tw/'),
    (506, '長榮大學', 4, 'https://www.cjcu.edu.tw/'),
    (507, '中國醫藥大學', 4, 'https://www.cmu.edu.tw/'),
    (508, '亞洲大學', 4, 'https://www.asia.edu.tw/'),
    (509, '開南大學', 4, 'https://www.knu.edu.tw/'),
    (510, '康寧學校財團法人康寧大學', 4, 'http://www.ukn.edu.tw/'),
    (511, '馬偕學校財團法人馬偕醫學院', 4, 'https://www.mmc.edu.tw/'),
    (512, '嘉藥學校財團法人嘉南藥理大學', 4, 'http://www.cnu.edu.tw/'),
    (513, '輔英科技大學', 4, 'https://www.fy.edu.tw/'),
    (514, '弘光科技大學', 4, 'https://www.hk.edu.tw/'),
    (515, '大仁科技大學', 4, 'https://www.tajen.edu.tw/'),
    (516, '中臺科技大學', 4, 'https://www.ctust.edu.tw/'),
    (517, '光宇學校財團法人元培醫事科技大學', 4, 'https://www.ypu.edu.tw/'),
    (518, '中華醫事科技大學', 4, 'http://www.hwai.edu.tw/'),
    (519, '美和學校財團法人美和科技大學', 4, 'http://www.meiho.edu.tw/'),
    (520, '吳鳳科技大學', 4, 'http://www.wfu.edu.tw/'),
    (521, '長庚學校財團法人長庚科技大學', 4, 'http://www.cgust.edu.tw/'),
    (522, '慈濟學校財團法人慈濟科技大學', 4, 'https://www.tcust.edu.tw/'),
    (523, '亞東技術學院', 4, 'https://www.oit.edu.tw/'),
    (524, '經國管理暨健康學院', 4, 'http://www.cku.edu.tw/'),
    (525, '馬偕學校財團法人馬偕醫護管理專科學校', 4, 'http://www.mkc.edu.tw/'),
    (526, '仁德醫護管理專科學校', 4, 'http://www.jente.edu.tw/'),
    (527, '樹人醫護管理專科學校', 4, 'http://www.szmc.edu.tw/'),
    (528, '慈惠醫護管理專科學校', 4, 'http://www.tzuhui.edu.tw/'),
    (529, '耕莘健康管理專科學校', 4, 'http://www.ctcn.edu.tw/'),
    (530, '敏惠醫護管理專科學校', 4, 'http://www.mhchcm.edu.tw/'),
    (531, '育英醫護管理專科學校', 4, 'https://www.yuhing.edu.tw/'),
    (532, '聖母醫護管理專科學校', 4, 'http://www.smc.edu.tw/'),
    (533, '新生醫護管理專科學校', 4, 'http://www.web.hsc.edu.tw/'),
    (534, '崇仁醫護管理專科學校', 4, 'http://www.cjc.edu.tw/'),
    (535, 'TVBS新聞', 5, 'https://news.tvbs.com.tw/'),
    (536, '民視新聞', 5, 'https://www.ftvnews.com.tw/'),
    (537, '中天新聞', 5, 'http://www.ctitv.com.tw/'),
    (538, '三立新聞台', 5, 'https://www.setn.com/'),
    (539, '東森新聞台', 5, 'https://news.ebc.net.tw/'),
    (540, '壹電視新聞台', 5, 'http://www.nexttv.com.tw/'),
    (541, '公視新聞台', 5, 'https://news.pts.org.tw/'),
    (542, '中視新聞台', 5, 'http://new.ctv.com.tw/News'),
    (543, '台視新聞台', 5, 'https://www.ttv.com.tw/news/'),
    (544, '年代新聞台', 5, 'http://www.eracom.com.tw/'),
    (545, '華視新聞台', 5, 'https://news.cts.com.tw/'),
    (546, '非凡新聞台', 5, 'https://www.ustv.com.tw/UstvMedia/'),
    (547, '大愛新聞台', 5, 'https://www.daai.tv/'),
    (548, '寰宇新聞台', 5, 'http://globalnewstv.com.tw/'),
    (549, 'ETtoday新聞雲', 5, 'https://www.ettoday.net/'),
    (550, '蘋果日報網站', 5, 'https://tw.appledaily.com/'),
    (551, 'udn聯合新聞網', 5, 'https://udn.com/'),
    (552, '自由時報電子報', 5, 'https://www.ltn.com.tw/'),
    (553, '中時電子報', 5, 'https://www.chinatimes.com/'),
    (554, '三立新聞網', 5, 'https://www.setn.com/'),
    (555, 'PNN公視新聞議題中心', 5, 'https://pnn.pts.org.tw/'),
    (556, '中央社即時新聞', 5, 'https://www.cna.com.tw/'),
    (557, '鏡週刊', 5, 'https://www.mirrormedia.mg/'),
    (558, 'TVBS新聞網', 5, 'https://news.tvbs.com.tw/'),
    (559, '東森新聞網', 5, 'https://news.ebc.net.tw/'),
    (560, '風傳媒', 5, 'https://www.storm.mg/'),
    (561, 'NOWnews今日新聞', 5, 'https://www.nownews.com/'),
    (562, 'The News Lens關鍵評論網', 5, 'https://www.thenewslens.com/'),
    (563, '新頭殼', 5, 'https://newtalk.tw/'),
    (564, '報導者', 5, 'https://www.twreporter.org/'),
    (565, '信傳媒', 5, 'https://www.cmmedia.com.tw/'),
    (566, 'Kairos風向新聞', 5, 'https://kairos.news/'),
    (567, '上報', 5, 'https://www.upmedia.mg/'),
    (568, 'Line(Line Today)', 5, 'https://today.line.me/tw/v2/tab'),
    (569, 'Google新聞', 5, 'https://news.google.com.tw/'),
    (570, 'Yahoo新聞網頁版', 5, 'https://tw.news.yahoo.com/'),
    (571, 'Yahoo新聞app', 5, 'https://tw.news.yahoo.com/app-phone'),
    (572, 'News Republic', 5, 'https://www.news-republic.com/'),
    (573, 'Flipboard', 5, 'https://flipboard.com/'),
    (574, '常春月刊', 6, 'https://www.ttvc.com.tw/'),
    (575, '康健雜誌', 6, 'https://www.commonhealth.com.tw/'),
    (576, '天下雜誌', 6, 'https://www.cw.com.tw/'),
    (577, '科學人雜誌', 6, 'https://sa.ylib.com/'),
    (578, '中時電子報', 6, 'https://www.chinatimes.com/');
    ALTER TABLE `WhiteList` ADD PRIMARY KEY (`WhiteListId`);
    ALTER TABLE `WhiteList` MODIFY `WhiteListId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=579;
    ";
    $conn->exec($SQL);
}
else
{
    $SQL = "
    DROP TABLE IF EXISTS `sentence`;
    DROP TABLE IF EXISTS `searchresult`;
    DROP TABLE IF EXISTS `search`;

    
    CREATE TABLE IF NOT EXISTS `search` (
    `SearchId` int(11) NOT NULL,
    `SearchString` varchar(100) NOT NULL,
    `SearchEmail` varchar(1000) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `search` ADD PRIMARY KEY (`SearchId`);
    ALTER TABLE `search` MODIFY `SearchId` int(11) NOT NULL AUTO_INCREMENT;

    
    CREATE TABLE IF NOT EXISTS `searchresult` (
    `SearchResultId` int(11) NOT NULL,
    `SearchId` int(11) NOT NULL,
    `WhiteListId` int(11) NOT NULL DEFAULT '0',
    `SearchResultRate` double NOT NULL,
    `Link` varchar(1000) NOT NULL,
    `Title` varchar(1000) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `searchresult` ADD PRIMARY KEY (`SearchResultId`);
    ALTER TABLE `searchresult` MODIFY `SearchResultId` int(11) NOT NULL AUTO_INCREMENT;
    ALTER TABLE `searchresult` ADD  CONSTRAINT `SearchId` FOREIGN KEY (`SearchId`) REFERENCES `search`(`SearchId`) ON DELETE CASCADE ON UPDATE RESTRICT;

    
    CREATE TABLE IF NOT EXISTS `sentence` (
    `sentence_id` int(11) NOT NULL,
    `search_result_id` int(11) NOT NULL,
    `sentences` longtext NOT NULL,
    `sentence_grade` double NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    ALTER TABLE `sentence` ADD PRIMARY KEY (`sentence_id`), ADD KEY `search_result_id` (`search_result_id`);
    ALTER TABLE `sentence` MODIFY `sentence_id` int(11) NOT NULL AUTO_INCREMENT;
    ALTER TABLE `sentence` ADD CONSTRAINT `search_result_id` FOREIGN KEY (`search_result_id`) REFERENCES `searchresult` (`SearchResultId`);
    ";
    $conn->exec($SQL);
}
echo "Success";
?>
